### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getURI' of undefined  when changing encoding on atom preferences.

### ISSUE THREAD

**Issue by neu-rah** [neu-rah/recall-file-encoding#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [recall-file-encoding](https://github.com/neu-rah/recall-file-encoding) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getURI' of undefined

```
At /home/azevedo/github/recall-file-encoding/lib/recall-file-encoding.coffee:16

TypeError: Cannot read property 'getURI' of undefined
    at Object.handleEncSave (/home/azevedo/github/recall-file-encoding/lib/recall-file-encoding.coffee:16:17)
    at /home/azevedo/github/recall-file-encoding/lib/recall-file-encoding.coffee:27:10
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/text-editor.js:515:32
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.setEncoding (/app.asar/node_modules/text-buffer/lib/text-buffer.js:333:22)
    at TextEditor.module.exports.TextEditor.update (/app.asar/src/text-editor.js:319:25)
    at /app.asar/src/text-editor-registry.js:384:26
    at Set.forEach (native)
    at /app.asar/src/text-editor-registry.js:382:50
    at /app.asar/src/config.js:897:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/app.asar/node_modules/settings-view/lib/settings-panel.js:201:28)
    at /app.asar/node_modules/settings-view/lib/settings-panel.js:215:26)
    at HTMLSelectElement.dispatch (/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSelectElement.elemData.handle (/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:00.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -1:10.2.0 encoding-selector:show (atom-text-editor.editor)
     -0:07.4.0 application:show-settings (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.10.1 
build 0.67.0 
busy 0.7.0 
command-toolbar 1.0.12 
file-icons 2.1.2 
git-plus 7.3.3 
ide-haskell 1.9.6 
intentions 1.1.2 
language-asp 1.0.0 
language-asp-html 0.3.0 
language-ini 1.19.0 
latex-completions 0.3.2 
linter 2.1.2 
linter-gcc 0.7.1 
linter-ui-default 1.2.2 
minimap 4.27.1 
platformio-ide 2.0.0-beta.2 
platformio-ide-terminal 2.5.0 
project-manager 3.3.4 
recall-file-encoding 0.2.0 
Remote-FTP 0.10.7 
selection-highlight 0.1.6 
tool-bar 1.1.0 
tree-view-git-status 1.3.1 
```

**Comment by neu-rah** [comment]
fixed https://github.com/neu-rah/recall-file-encoding/commit/6adbc08930d10c030346b7a0e08becd947897679
